spring.application.name=laEspigabackend

spring.datasource.url=jdbc:postgresql://ep-autumn-union-adh2gt52-pooler.c-2.us-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_UxKCtkd9O8GY

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.security=DEBUG
logging.level.com.laespiga.laespigabackend.config=DEBUG

jwt.secret=${JWT_SECRET}
jwt.expiration=864400000
server.port=${PORT:8080}

# --- ACTUATOR & PROMETHEUS ---
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

# --- CONFIGURACION EMAIL (GMAIL EJEMPLO) ---
# Debes generar una "Contraseña de Aplicacion" en tu cuenta de Google
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=laespiga0120@gmail.com
spring.mail.password=ymlkfapcbxdaatgi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

