spring.application.name=fastory-backend

# --- CONEXIÓN A SUPABASE (PgBouncer Transaction Mode) ---
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:6543/postgres}?prepareThreshold=0
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.ikawgnldazdayneqegjv}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:h7QPD6pO3gTTX9S3}

# --- JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# --- LOGGING ---
logging.level.org.springframework.security=DEBUG
logging.level.com.fastory.fastorybackend.config=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# --- JWT ---
jwt.secret=${JWT_SECRET:fastory-super-secret-key-for-testing-only-32chars}
jwt.expiration=864400000
server.port=${PORT:8080}

# --- ACTUATOR & PROMETHEUS ---
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

# --- CONFIGURACION EMAIL (GMAIL EJEMPLO) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=laespiga0120@gmail.com
spring.mail.password=ymlkfapcbxdaatgi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
